server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: beyzanur

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true


